# permissions for end users to view configdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configdeployment-viewer-role
rules:
- apiGroups:
  - demo.walk1ng.dev
  resources:
  - configdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.walk1ng.dev
  resources:
  - configdeployments/status
  verbs:
  - get
