# permissions for end users to edit configdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configdeployment-editor-role
rules:
- apiGroups:
  - demo.walk1ng.dev
  resources:
  - configdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.walk1ng.dev
  resources:
  - configdeployments/status
  verbs:
  - get
