apiVersion: webapp.walk1ng.dev/v1
kind: Employee
metadata:
  name: benjamin
spec:
  # Add fields here
  role: manager
  company: microsoft
  desiredWorkers: 3
  resources:
    limits:
      cpu: 50m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 100Mi
