apiVersion: webapp.walk1ng.dev/v1
kind: Employee
metadata:
  name: klose
spec:
  # Add fields here
  role: engineer
  company: microsoft
  resources:
    limits:
      cpu: 50m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 100Mi
