
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.walk1ng.dev
  resources:
  - nicepods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.walk1ng.dev
  resources:
  - nicepods/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.walk1ng.dev
  resources:
  - nicepods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - webapp.walk1ng.dev
  resources:
  - niceservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.walk1ng.dev
  resources:
  - niceservices/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.walk1ng.dev
  resources:
  - niceservices/status
  verbs:
  - get
  - patch
  - update
