
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-webapp-walk1ng-dev-v1-company
  failurePolicy: Fail
  name: mcompany.kb.io
  rules:
  - apiGroups:
    - webapp.walk1ng.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - companies
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-webapp-walk1ng-dev-v1-company
  failurePolicy: Fail
  name: vcompany.kb.io
  rules:
  - apiGroups:
    - webapp.walk1ng.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - companies
  sideEffects: None
