apiVersion: v1
kind: Service
metadata:
  name: edge-service
spec:
  type: NodePort
  selector:
    app: edge
  ports:
  - port: 8087
    targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-deployment
spec:
  selector:
    matchLabels:
      app: edge
  template:
    metadata:
      labels:
        app: edge
    spec:
      containers:
      - name: edge
        image: walk1ng/edge-mgr-proto:v0.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8087
          name: http
