apiVersion: webapp.walk1ng.dev/v1
kind: GuestBook
metadata:
  name: guestbook-sample
spec:
  # Add fields here
  redisName: "redis-sample"
  frontend: 
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    ServingPort: 8081
