apiVersion: v1
kind: Service
metadata:
  name: my-golang-app
spec:
  selector:
    app: my-golang-app
  ports:
  - port: 2345
    targetPort: 2345
    nodePort: 31111
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: my-golang-app
  labels:
    app: my-golang-app
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName: "unconfined"
spec:
  nodeName: mynode
  containers:
    - name: my-golang-app
      image: my-golang-app-image:latest
      imagePullPolicy: Never
      resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
      ports:
        - containerPort: 2345
          # hostPort: 2345 # can be exposed by NodePort