# permissions for end users to view employees.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: employee-viewer-role
rules:
- apiGroups:
  - webapp.walk1ng.dev
  resources:
  - employees
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.walk1ng.dev
  resources:
  - employees/status
  verbs:
  - get
