
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapp.walk1ng.dev
  resources:
  - companies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.walk1ng.dev
  resources:
  - companies/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.walk1ng.dev
  resources:
  - companies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - webapp.walk1ng.dev
  resources:
  - employees
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.walk1ng.dev
  resources:
  - employees/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.walk1ng.dev
  resources:
  - employees/status
  verbs:
  - get
  - patch
  - update
